#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp.

# Display usage if less than 4 parameters are passed

msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ "$4" ]; then
   scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ]; then
     scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "$msg";
fi
