#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend tenderheart.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 225414-web-01 100.26.122.236:80
        server 225414-web-02 35.175.102.186:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
