#!/usr/bin/env bash

#!/bin/bash

# Get a list of all processes with their hierarchies
process_list=$(ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest)

# Print the header
printf "%-10s %-10s %-4s %-4s %-6s %-6s %-6s %-6s %-10s %-10s %s\n" \
	  "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "TIME" "COMMAND"

# Loop through each line of the process list and print the details
while IFS= read -r line; do
	  printf "%s\n" "$line"
  done <<< "$process_list"
