#!/usr/bin/env bash
# Bash script to display information from /etc/passwd using a while loop and IFS.

# Path to the /etc/passwd file
passwd_file="/etc/passwd"

# Using a while loop to read each line of the /etc/passwd file
while IFS=: read -r username _ userid groupid _ user_info home_directory shell; do
    # Displaying formatted information for each user
    echo "The user $username is part of the $groupid gang,"
    echo "lives in $home_directory and rides $shell."
    echo "USER ID's place is protected by the passcode PASSWORD, more info about the user here: $user_info"
    echo
done < "$passwd_file"

