#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop.

# Initialize a counter
counter=0

# Using a while loop to repeat the echo statement until the counter reaches 10
while [ "$counter" -lt 10 ]; do
    echo "Best School"
    
    # Increment the counter
    ((counter++))
done

